name: Java CI with Ant

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # you can use 'zulu' or others too
        java-version: '17'       # or '11', depending on your project

    - name: Install Ant
      run: |
        sudo apt-get update
        sudo apt-get install ant

    - name: Build with Ant
      run: ant
